
var tipuesearch = {"pages": [
  {"title": "Homepage", "text": "The Office of the Federal Chief Sustainability Officer (CSO) leads development of policies, programs, and partnerships to advance sustainability and climate resilient Federal operations. The Office of the Federal CSO is part of the White House Council on Environmental Quality.", "tags": "", "url": "https://www.sustainability.gov/index.html"},
  
  {"title": "Federal Progress, Plans, and Performance", "text": "Federal agencies continue to demonstrate progress and performance on energy efficiency and sustainability. See agency-specific and government-wide progress and recent agency scorecards.", "tags": "", "url": "https://www.sustainability.gov/progress.html"},
  
  {"title": "Federal Sustainability Resources and Guidance", "text": "This page provides links to CEQ guidance and Federal resources for sustainability, energy, and environmental performance such as Executive Order 14057 Implementing Instructions, Guiding Principles for Sustainable Federal Buildings and Associated Instructions, and Federal Greenhouse Gas Accounting and Reporting Guidance.", "tags": "", "url": "https://www.sustainability.gov/resources.html"},
  
  {"title": "About the Office of the Federal Chief Sustainability Officer", "text": "Along with agency partners, the Office of Federal Chief Sustainability Officer is leading the development of the Federal Government's plan to create jobs and stimulate clean energy industries by revitalizing sustainability efforts, transitioning the Federal fleet to U.S.-manufactured zero emission vehicles and powering Federal operations using 100 percent 24/7 carbon pollution-free electricity.", "tags": "", "url": "https://www.sustainability.gov/about.html"},     
  
  {"title": "Agency Chief Sustainability Officers", "text": "Federal agencies appoint an Agency Chief Sustainability Officer to lead agency-wide implementation of sustainability and climate adaptation policy and meet the President's goals and priorities.", "tags": "", "url": "https://www.sustainability.gov/about_cso.html"},     
     
  {"title": "Federal Agency Progress Data and Scorecard Archive", "text": "This page features agencies' previous years' data and scorecards.", "tags": "", "url": "https://www.sustainability.gov/archive.html"},
     
  {"title": "Archived Guidance and Resources", "text": "The policy and guidance documents on this page are no longer in effect, do not represent current Administration positions, and are provided for reference purposes only.", "tags": "", "url": "https://www.sustainability.gov/archived-resources.html"},
     
  {"title": "Contact the Office of the Federal Chief Sustainability Officer", "text": "Access contact information for the Office of the Federal Chief Sustainability Officer", "tags": "", "url": "https://www.sustainability.gov/contact.html"},
     
  {"title": "Contributing Agencies Annual Sustainability Report and Implementation Plans", "text": "Contributing agencies have smaller operational footprints and may not manage facilities or vehicle fleets. These agencies have voluntarily developed and submitted abbreviated annual Sustainability Report and Implementation Plans specific to their operations.", "tags": "", "url": "https://www.sustainability.gov/contributing-agencies.html"},
     
  {"title": "Department of Homeland Security Agency Progress", "text": "The Department of Homeland Security's recent annual Climate Adaptation Plans and Reports, OMB Scorecards for Efficient Operations and Management, and historical performance data toward energy and sustainability goals are featured.", "tags": "", "url": "https://www.sustainability.gov/dhs.html"},
     
  {"title": "Department of Commerce Agency Progress", "text": "The Department of Commerce's recent annual Climate Adaptation Plans and Reports, OMB Scorecards for Efficient Operations and Management, and historical performance data toward energy and sustainability goals are featured.", "tags": "", "url": "https://www.sustainability.gov/doc.html"},     
     
  {"title": "Department of Defense Agency Progress", "text": "The Department of Defense's recent annual Climate Adaptation Plans and Reports, OMB Scorecards for Efficient Operations and Management, and historical performance data toward energy and sustainability goals are featured.", "tags": "HTML", "url": "https://www.sustainability.gov/dod.html"},
     
  {"title": "Department of Energy Agency Progress", "text": "The Department of Energy's recent annual Climate Adaptation Plans and Reports, OMB Scorecards for Efficient Operations and Management, and historical performance data toward energy and sustainability goals are featured.", "tags": "", "url": "https://www.sustainability.gov/doe.html"},
     
  {"title": "Department of the Interior Agency Progress", "text": "The Department of the Interior's recent annual Climate Adaptation Plans and Reports, OMB Scorecards for Efficient Operations and Management, and historical performance data toward energy and sustainability goals are featured.", "tags": "", "url": "https://www.sustainability.gov/doi.html"},
  
  {"title": "Department of Justice Agency Progress", "text": "The Department of Justice's recent annual Climate Adaptation Plans and Reports, OMB Scorecards for Efficient Operations and Management, and historical performance data toward energy and sustainability goals are featured.", "tags": "", "url": "https://www.sustainability.gov/doj.html"},
  
  {"title": "Department of Labor Agency Progress", "text": "The Department of Labor's recent annual Climate Adaptation Plans and Reports, OMB Scorecards for Efficient Operations and Management, and historical performance data toward energy and sustainability goals are featured.", "tags": "", "url": "https://www.sustainability.gov/dol.html"},
  
  {"title": "Department of Transportation Agency Progress", "text": "The Department of Transportation's recent annual Climate Adaptation Plans and Reports, OMB Scorecards for Efficient Operations and Management, and historical performance data toward energy and sustainability goals are featured.", "tags": "", "url": "https://www.sustainability.gov/dot.html"},
  
  {"title": "Environmental Protection Agency Agency Progress", "text": "The Environmental Protection Agency's recent annual Climate Adaptation Plans and Reports, OMB Scorecards for Efficient Operations and Management, and historical performance data toward energy and sustainability goals are featured.", "tags": "", "url": "https://www.sustainability.gov/epa.html"},
  
  {"title": "Federal Government-Wide Performance Data", "text": "The Federal government is the largest energy consumer in the nation, managing more than 300,000 buildings and 600,000 vehicles. By increasing the efficiency of Federal operations, Federal agencies cut waste, save taxpayer dollars, reduce impacts on the environment, and promote clean air, land, and water.", "tags": "", "url": "https://www.sustainability.gov/government_data.html"},

  {"title": "General Services Administration Agency Progress", "text": "General Services Administration's recent annual Climate Adaptation Plans and Reports, OMB Scorecards for Efficient Operations and Management, and historical performance data toward energy and sustainability goals are featured.", "tags": "", "url": "https://www.sustainability.gov/gsa.html"},

  {"title": "Department of Health and Human Services Agency Progress", "text": "The Department of Health and Human Services's recent annual Climate Adaptation Plans and Reports, OMB Scorecards for Efficient Operations and Management, and historical performance data toward energy and sustainability goals are featured.", "tags": "", "url": "https://www.sustainability.gov/hhs.html"},

  {"title": "Department of Housing and Urban Development Agency Progress", "text": "The Department of Housing and Urban Development's recent annual Climate Adaptation Plans and Reports, OMB Scorecards for Efficient Operations and Management, and historical performance data toward energy and sustainability goals are featured.", "tags": "", "url": "https://www.sustainability.gov/hud.html"},

  {"title": "Who We Are", "text": "As the Federal Chief Sustainability Officer, Andrew Mayock leads President Biden's efforts to improve the sustainability of the Federal government, including by helping Federal agencies prepare for and respond to the impacts of climate change on their operations and services. Dee Siegel is the Deputy Chief Sustainability Officer in the Office of the CSO, where she works with Federal agencies, external stakeholders, and offices within the White House to promote sustainability across Federal government operations. ", "tags": "", "url": "https://www.sustainability.gov/whoweare.html"},

  {"title": "National Archives and Records Administration Agency Progress", "text": "The National Archives and Records Administration's recent annual Climate Adaptation Plans and Reports, OMB Scorecards for Efficient Operations and Management, and historical performance data toward energy and sustainability goals are featured.", "tags": "", "url": "https://www.sustainability.gov/nara.html"},

  {"title": "National Aeronautics and Space Administration Agency Progress", "text": "The National Aeronautics and Space Administration's recent annual Climate Adaptation Plans and Reports, OMB Scorecards for Efficient Operations and Management, and historical performance data toward energy and sustainability goals are featured.", "tags": "", "url": "https://www.sustainability.gov/nasa.html"},

  {"title": "Smithsonian Institution Agency Progress", "text": "The Smithsonian Institution's recent annual Climate Adaptation Plans and Reports, OMB Scorecards for Efficient Operations and Management, and historical performance data toward energy and sustainability goals are featured.", "tags": "", "url": "https://www.sustainability.gov/si.html"},

  {"title": "Social Security Administration Agency Progress", "text": "The Social Security Administration's recent annual Climate Adaptation Plans and Reports, OMB Scorecards for Efficient Operations and Management, and historical performance data toward energy and sustainability goals are featured.", "tags": "", "url": "https://www.sustainability.gov/ssa.html"},

  {"title": "Department of State Agency Progress", "text": "Department of State's recent annual Climate Adaptation Plans and Reports, OMB Scorecards for Efficient Operations and Management, and historical performance data toward energy and sustainability goals are featured.", "tags": "", "url": "https://www.sustainability.gov/state.html"},

  {"title": "Department of the Treasury Agency Progress", "text": "Department of the Treasury's recent annual Climate Adaptation Plans and Reports, OMB Scorecards for Efficient Operations and Management, and historical performance data toward energy and sustainability goals are featured.", "tags": "", "url": "https://www.sustainability.gov/treasury.html"},
  
  {"title": "Tennessee Valley Authority Agency Progress", "text": "Tennessee Valley Authority's recent annual Climate Adaptation Plans and Reports, OMB Scorecards for Efficient Operations and Management, and historical performance data toward energy and sustainability goals are featured.", "tags": "", "url": "https://www.sustainability.gov/tva.html"},
  
  {"title": "Army Corps of Engineers Agency Progress", "text": "Army Corps of Engineers' recent annual Climate Adaptation Plans and Reports, OMB Scorecards for Efficient Operations and Management, and historical performance data toward energy and sustainability goals are featured.", "tags": "", "url": "https://www.sustainability.gov/usace.html"},
  
  {"title": "Department of Agriculture Agency Progress", "text": "Department of Agriculture's recent annual Climate Adaptation Plans and Reports, OMB Scorecards for Efficient Operations and Management, and historical performance data toward energy and sustainability goals are featured.", "tags": "", "url": "https://www.sustainability.gov/usda.html"},
  
  {"title": "U.S. Postal Service Agency Progress", "text": "U.S. Postal Service's recent annual Climate Adaptation Plans and Reports, OMB Scorecards for Efficient Operations and Management, and historical performance data toward energy and sustainability goals are featured.", "tags": "", "url": "https://www.sustainability.gov/usps.html"},
  
  {"title": "Department of Veterans Affairs Agency Progress", "text": "Department of Veterans Affairs' recent annual Climate Adaptation Plans and Reports, OMB Scorecards for Efficient Operations and Management, and historical performance data toward energy and sustainability goals are featured.", "tags": "", "url": "https://www.sustainability.gov/va.html"},
  
  {"title": "Energy and Environmental Policies", "text": "A page listing statutes and Executive Orders that have established Federal policies for energy and sustainability management. These include E.O. 14057, 14008, 14030, 13990, Energy Act of 2020, Energy Independence and Security Act of 2007, Energy Policy Act of 2005, Energy Policy Act of 1992, National Energy Conservation Policy Act of 1978, Resource Conservation and Recovery Act of 1976, and Farm Security and Rural Investment Act of 2002.", "tags": "", "url": "https://www.sustainability.gov/policy.html"},
  
  {"title": "Resources and Guidance by Topic", "text": "U.S. Code, public law, guidance, and Federal resources by topic. Topics include facility energy efficiency, renewable energy and electricity, water management, performance contracting, high performance sustainable buildings, waste management, acquisition and electronics stewardship, performance tracking and reporting, and fleet management.", "tags": "", "url": "https://www.sustainability.gov/resources-eo-efo.html"},
  
  {"title": "Federal Sustainability Plan", "text": "The Federal Sustainability Plan sets out a range of medium- and long-term targets and actions designed to deliver an emissions reduction pathway consistent with the 1.5 ambition of the Paris Agreement.", "tags": "", "url": "https://www.sustainability.gov/federalsustainabilityplan/index.html"},
  
  {"title": "Letter from the President of the United States", "text": "In conjunction with the release of the Federal Sustainability Plan, President Biden issued a message to the Federal workforce.", "tags": "", "url": "https://www.sustainability.gov/message.html"},
  
  {"title": "Federal Agencies Leading by Example", "text": "Federal agencies and military installations across the country are taking action now to implement the President's Federal Sustainability Plan and Executive Order. Learn how agencies are leading by example or view the interactive map, using the filter to find projects based on your interest.", "tags": "", "url": "https://www.sustainability.gov/leadingbyexample.html"},
  
  {"title": "100% Carbon-Pollution Free Electricity", "text": "President Biden's Federal Sustainability Plan outlines an ambitious path to power Federal infrastructure twenty-four hours, seven days a week (24/7) with carbon pollution-free electricity (CFE) by 2035. It adds Federal leadership to CFE commitments being made by public, private, and non-profit leaders across America and around the world.", "tags": "", "url": "https://www.sustainability.gov/federalsustainabilityplan/carbon.html"},
  
  {"title": "100% Zero-Emission Vehicle Fleet", "text": "President Biden's Federal Sustainability Plan sets the Federal fleet on a path to zero-emission vehicles (ZEVs). His plan will help further accelerate a rapidly changing transportation sector and further increase well-paying union jobs and support emission reductions in pollution overburdened communities. It establishes the Federal Government as a leader in clean transportation and builds upon commitments being made by public, private, and non-profit leaders across America and around the world.", "tags": "", "url": "https://www.sustainability.gov/federalsustainabilityplan/fleet.html"},
  
  {"title": "Net-Zero Emissions Buildings", "text": "President Biden's Federal Sustainability Plan outlines an ambitious path to achieve a net-zero emission buildings goal by 2045. The Federal Government will work across new building construction, major renovations, and existing real property to electrify systems, decrease energy use, reduce water consumption and cut waste. Federal agencies will set ambitious, data-driven 2030 goals and annual targets for energy and water reductions, based on leading performance benchmarks for building type categories and the composition of the agency's building portfolio.", "tags": "", "url": "https://www.sustainability.gov/federalsustainabilityplan/buildings.html"},
  
  {"title": "Net-Zero Procurement and Supply Chains", "text": "President Biden's Federal Sustainability Plan outlines an ambitious path to achieve net-zero emissions from Federal procurement by 2050 while increasing the sustainability of Federal supply chains. These supply chain initiatives include major contractor greenhouse gas (GHG) emission disclosures paired with science-based targets, a buy clean initiative for low-carbon materials, and a sustainable products policy. These programs will advance America's industrial competitiveness to supply the low-carbon and sustainable goods of the future while creating well-paying union jobs.", "tags": "", "url": "https://www.sustainability.gov/federalsustainabilityplan/procurement.html"},
  
  {"title": "Federal Buy Clean Initiative", "text": "To harness that procurement power to support low-carbon, made in America materials, President's Biden charged his Administration through his December 2021 Federal Sustainability Plan and Executive Order 14057 to launch a Buy Clean Task Force and initiative to promote use of low-carbon, made in America construction materials. Through Buy Clean, the Federal Government will for the first time prioritize the use of American-made, lower-carbon construction materials in Federal procurement and Federally-funded projects, which will advance America's industrial capacity to supply the goods and materials of the future while growing good jobs for American workers.", "tags": "", "url": "https://www.sustainability.gov/buyclean/index.html"},
  
  {"title": "Net-Zero Emissions Federal Operations", "text": "President Biden's Federal Sustainability Plan outlines an ambitious path to achieve net-zero emissions across Federal operations by 2050. To achieve this goal, the Federal Government will transition its infrastructure to zero-emission vehicles (ZEVs) and buildings, powered by carbon pollution-free electricity (CFE). It also will transform its operations to develop a net-zero supply chain, require Federal agencies to set goals to reduce greenhouse gas (GHG) emissions, and partner with leading domestic and international organizations to accelerate progress.", "tags": "", "url": "https://www.sustainability.gov/federalsustainabilityplan/emissions.html"},
  
  {"title": "Climate Resilient Policy, Programs, Operations and Infrastructure", "text": "President Biden's Federal Sustainability Plan outlines an ambitious path to prepare Federal agency policy, programs, operations, and infrastructure to adopt adaptive and resilient strategies for future climate impacts. Federal agencies will develop climate adaptation and resilience plans that evaluate the most significant climate-related risks and vulnerabilities for agency operations and missions, and identify action to manage those risks and vulnerabilities. The President's Federal Sustainability Plan also establishes the Climate Adaptation and Resilience Federal Leaders Working Group, which will advance agency coordination, continual learning, and implementation in areas such as climate data and tools, infrastructure adaptation, and adaptation metrics and evaluation. ", "tags": "", "url": "https://www.sustainability.gov/federalsustainabilityplan/resilience.html"},
  
  {"title": "Engaging, Educating, and Training the Federal Workforce", "text": "President Biden's Federal Sustainability Plan outlines an ambitious path to mainstream sustainability within the Federal workforce. The Plan's elements build internal capacity through engagement, education, and training on Federal sustainability, climate adaptation, and environmental stewardship. Federal agencies also will incorporate sustainability and climate adaptation into their human capital planning, including optimal staffing, training, and associated resources.", "tags": "", "url": "https://www.sustainability.gov/federalsustainabilityplan/workforce.html"},
  
  {"title": "Sustainability Speaker Series for the Federal Community", "text": "In support of President Biden's Federal Sustainability Plan, the Biden Administration is launching an interactive speaker series for Federal employees to hear from dynamic and thought-provoking leaders and innovators within the climate and sustainability space. Through this series, employees will enhance their sustainability and climate literacy, learn more about the President's Federal Sustainability Plan and their critical role in the shift to more sustainable and resilient operations. Speakers have included Al Roker, Donnel Baird, Bill Nye, and Dr. Katharine Hayhoe.", "tags": "", "url": "https://www.sustainability.gov/sustainability-series.html"},
  
  {"title": "Advancing Environmental Justice and Equity", "text": "President Biden's Federal Sustainability Plan outlines an ambitious path to create a more equitable future for America by incorporating environmental justice and equity into Federal sustainability. Federal agencies will consider the goals of the Justice40 Initiative when making decisions related to Federal facilities, fleets, and operations. To incorporate equity, agencies will support Executive Order 13985, Advancing Racial Equity and Support for Underserved Communities Through the Federal Government.", "tags": "", "url": "https://www.sustainability.gov/federalsustainabilityplan/justice.html"},
  
  {"title": "Accelerating Progress Through Partnerships", "text": "President Biden's Federal Sustainability Plan outlines an ambitious path to leverage domestic and international partnerships to accelerate progress and catalyze greater action at home and abroad. We will place senior leaders from the private and non-profit sectors into limited-term appointments to bring innovative perspectives and expertise to assist Federal agencies with sustainability and climate preparedness efforts.", "tags": "", "url": "https://www.sustainability.gov/federalsustainabilityplan/partnerships.html"},
  
  {"title": "News and Updates", "text": "News and updates from the Office of the Federal Chief Sustainability Officer", "tags": "", "url": "https://www.sustainability.gov/newsroom.html"},
  
  {"title": "Greening Government Initiative", "text": "In April 2021, the United States and Canada launched a new global effort—the Greening Government Initiative (GGI)—to engage and support governments around the world in greening national government operations. This first-of-its-kind international community of practice will enable countries to share knowledge and lessons learned, promote innovation, and help meet Paris Agreement commitments.", "tags": "", "url": "https://www.sustainability.gov/ggi/index.html"}, 
  
  {"title": "Infographic: Scope of Greening Government Initiative", "text": "Infographic illustrates examples of the scope of the Greening Government Initiative (GGI) and the intersection of GGI with other efforts.", "tags": "", "url": "https://www.sustainability.gov/ggi/scope.html"},
  
  {"title": "Countries and Year Joining GGI", "text": "All countries can participate in Greening Government Initiative (GGI). To be considered a GGI participating country, a country representative endorses the GGI Concept Note. View the list of participating GGI countries and the year they joined.", "tags": "", "url": "https://www.sustainability.gov/ggi/countries.html"},
  
  {"title": "Greening Government Initiative Countries", "text": "Learn how each of the GGI countries is greening its government.", "tags": "", "url": "https://www.sustainability.gov/ggi/country-details.html"},

  {"title": "Interactive Map: Federal Agencies Leading by Example", "text": "Federal agencies across the country are taking action now to implement the President's Federal Sustainability Plan and Executive Order.", "tags": "", "url": "https://www.sustainability.gov/map/index.html"},  

  {"title": "Federal Sustainability Plan Strategy Matrix", "text": "This matrix outlines the goals, actions, and focus areas of the Federal Sustainability Plan.", "tags": "", "url": "https://www.sustainability.gov/map/index.html"}
  
]};



